<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle</name>
   <tag></tag>
   <elementGuidId>563b09df-22a0-4ead-8cff-79f000df1e55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>g > circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>a1e01e88-01d4-4e57-af03-5dcd795dd307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>14.4</value>
      <webElementGuid>834fab9a-edb9-43fa-9317-6dc0280dfffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>14.4</value>
      <webElementGuid>4787aeb8-2b6f-41a5-bdde-7a2420196db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>14.4</value>
      <webElementGuid>213d5bbd-f6d2-4896-824c-dc4e54053243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#E5E5E5</value>
      <webElementGuid>b5292ad9-c263-4a11-84aa-3a21a7ef6331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill-opacity</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>12be6b22-5583-403f-981b-dc03e8db4ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-item-3&quot;)/span[@class=&quot;sc-rq82e3-0 mzbNL&quot;]/svg[1]/g[1]/circle[1]</value>
      <webElementGuid>8721acc8-370d-4546-9b26-9d234ee15c62</webElementGuid>
   </webElementProperties>
</WebElementEntity>
