<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat Email atau Nomor HP_sc-1auyczi_6f84f0</name>
   <tag></tag>
   <elementGuidId>e574096d-0cc8-4bbd-b70b-997a767dbdb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.sc-1auyczi-2.bIZmZe.sc-1uj1rn4-2.gFJWwS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0dabc6ce-62b6-4dbc-a578-5b4c97c156a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>9d79a81c-afb0-45f0-891f-43c75bbd0ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9349764e-b50d-4214-9ae4-a1d6146cd3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-1auyczi-2 bIZmZe sc-1uj1rn4-2 gFJWwS</value>
      <webElementGuid>e5cefde8-c96d-4c12-8e70-721c5de949b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>1e2f2a0b-9c90-4762-a561-77dc7206ae95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;sc-vswk66-0 fJiAhm&quot;]/div[@class=&quot;sc-rkmhgf-0 hWVtzq&quot;]/div[@class=&quot;sc-1crxk01-0 gVKylD&quot;]/div[@class=&quot;sc-1crxk01-0 kllYhf&quot;]/div[@class=&quot;sc-1crxk01-0 inhaeL&quot;]/div[@class=&quot;sc-1uj1rn4-3 iuAPRv&quot;]/input[@class=&quot;sc-1auyczi-2 bIZmZe sc-1uj1rn4-2 gFJWwS&quot;]</value>
      <webElementGuid>44c618cc-3016-4aae-adcd-08215852145d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>7327389c-f975-42b9-a106-e55099cac5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>b3e9bf0f-f68d-4e39-8a37-4a7e5baf64fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2b2011e3-709f-4be3-a5ff-fb65e826e2df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>695e7f59-93f9-42bb-ba68-ac7fa5c42705</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
