<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Profile</name>
   <tag></tag>
   <elementGuidId>bab78d76-8dae-4d27-af0d-3cc681ce4243</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-item-3 > p.bottom-nav-item--title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-item-3']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7db2236d-94c8-4625-9b10-9c5068a8b06a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bottom-nav-item--title</value>
      <webElementGuid>9c40215e-4317-4841-a737-2175a52aac87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Profile</value>
      <webElementGuid>fc79e88b-3983-4399-878e-aa9f48cbf81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-item-3&quot;)/p[@class=&quot;bottom-nav-item--title&quot;]</value>
      <webElementGuid>1f1bb425-3599-4f46-85c2-7f9deede87b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-item-3']/p</value>
      <webElementGuid>5a81079f-1380-400e-9bf7-c5e68f529364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Astraotoshop.com 2016 - 2021. All rights reserved.'])[1]/following::p[4]</value>
      <webElementGuid>4be1556a-3cc8-4c5b-abec-44b798d8adcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Booking Service'])[1]/following::p[4]</value>
      <webElementGuid>1afc129d-9042-4350-948d-94252d18af36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'nav-item-3', '&quot;', ')/p[@class=', '&quot;', 'bottom-nav-item--title', '&quot;', ']')])[1]/preceding::p[1]</value>
      <webElementGuid>9a22331e-9396-46d0-bd0a-3bbd25497f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Profile']/parent::*</value>
      <webElementGuid>a03587e1-7606-4f75-9bc5-ea49e45b32ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/p</value>
      <webElementGuid>46ccfea0-0254-4d73-95e6-7e39ec7122e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Profile' or . = 'Profile')]</value>
      <webElementGuid>90012a21-f522-4a95-932a-ff9d774e8e39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
