<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LoginBerryBenka</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>def4cac6-c786-4efe-973f-7ba1980d127a</testSuiteGuid>
   <testCaseLink>
      <guid>738957ee-2037-4d9f-ac3b-d23a8cf1f5b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DDTest/DataDrivenBerryBenka</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>46288946-d128-4429-acda-c664c58c7eb9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginBerryBenka</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>46288946-d128-4429-acda-c664c58c7eb9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>23ee67f9-cbbe-4c30-a94a-db88ab9772f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>46288946-d128-4429-acda-c664c58c7eb9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>c7ccbd8a-fdff-4829-9442-2d38d2aaaf5d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
