<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unggah file-file PDF  image_file</name>
   <tag></tag>
   <elementGuidId>8d54f031-4af3-4bb5-961e-cda5ca13ddeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;file&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='file']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fce63c8-986f-4885-8a8c-301a4a28263c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>https://uploads3.sejda.com/api/files/upload?_s=23</value>
      <webElementGuid>b8cf25d2-e8ea-4de5-9325-27f986891947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.pdf,.png,.gif,.jpg,.jpeg,.tif,.tiff,.bmp,.webp</value>
      <webElementGuid>ffe314bb-9769-48d8-be03-7d32cfa0d26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>38aa8ce7-ae17-4227-8011-aa51e81cc6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>8d7af65b-db9e-4af3-b9e2-4b013f5925af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-scope</name>
      <type>Main</type>
      <value>task-file</value>
      <webElementGuid>988e4a1c-c3ca-42d2-b293-98bb3de745a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>d8ee5084-81b1-4fd5-a103-044b08b14b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>fa221e56-70d8-4759-88f4-169b46a3450f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-allows-drop</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dad7c477-b4d8-4e6c-8cbf-e095d77b5c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fileupload</value>
      <webElementGuid>000ec654-ddce-47f8-83f1-4ea0006af834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fileUploadForm&quot;)/input[@class=&quot;fileupload&quot;]</value>
      <webElementGuid>de342f14-eea6-4222-9e84-50ae04f69021</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='file']</value>
      <webElementGuid>4397d1f1-8142-4df3-8718-5c75172801fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fileUploadForm']/input[3]</value>
      <webElementGuid>5f37dab8-bd0e-4122-810c-f6dacf2befc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>d955bf58-1542-473e-a76a-5c8fd1b6818e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Upload' and @name = 'file' and @type = 'file']</value>
      <webElementGuid>21d63808-754f-4dd0-9a51-5b4cdfa0950b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
