<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Learn CSS</name>
   <tag></tag>
   <elementGuidId>92f32865-283e-4db5-bb77-8b0ec6e23d87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='nav_tutorials']/div/div/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>954356de-5e77-4498-b6ab-9e04bed981d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-bar-item w3-button</value>
      <webElementGuid>a83c97ec-bb0b-4109-ac4c-5aae47dcef27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/css/default.asp</value>
      <webElementGuid>0b822abb-e042-4397-bb7c-6fabc56edb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Learn CSS</value>
      <webElementGuid>cc067e17-5f5c-417f-a0b0-0043e4f96d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav_tutorials&quot;)/div[@class=&quot;w3-content&quot;]/div[@class=&quot;w3-row-padding w3-bar-block&quot;]/div[@class=&quot;w3-col l3 m6&quot;]/a[@class=&quot;w3-bar-item w3-button&quot;]</value>
      <webElementGuid>d8102db4-5570-4b39-a811-83b89dab31d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='nav_tutorials']/div/div/div[2]/a[2]</value>
      <webElementGuid>47588fdb-e42e-44bc-995c-3bdcaf4d00af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Learn CSS')]</value>
      <webElementGuid>1869d93c-01ad-442c-9bff-9e8ea18416bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn HTML'])[1]/following::a[1]</value>
      <webElementGuid>79afcad5-8917-4a25-bd39-8fe9b4c1df92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HTML and CSS'])[1]/following::a[2]</value>
      <webElementGuid>f78b4230-a17f-443d-b730-cd1f19934ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn RWD'])[1]/preceding::a[1]</value>
      <webElementGuid>9d98c3ac-7f38-4c2c-b1a1-b8a89f8d7fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn Bootstrap'])[1]/preceding::a[2]</value>
      <webElementGuid>19895ad3-4352-48d1-8b33-a5048023cf06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Learn CSS']/parent::*</value>
      <webElementGuid>8fea8404-c482-4920-8bd2-28a09f702872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/css/default.asp')]</value>
      <webElementGuid>41fdf9e1-196c-4d68-a16f-e9dec9f4fb5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/a[2]</value>
      <webElementGuid>88f0883f-b172-4280-8adb-acdf847e29f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/css/default.asp' and (text() = 'Learn CSS' or . = 'Learn CSS')]</value>
      <webElementGuid>35e8e41a-3e2c-4bcd-8c57-cedb81b42a9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
