<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tutorials</name>
   <tag></tag>
   <elementGuidId>fb782c1a-1c9f-4b35-b850-e1fb8645c7c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navbtn_tutorials</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navbtn_tutorials']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c70d4596-2518-4b58-acd8-4622bff039b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-bar-item w3-button w3-hide-small barex bar-item-hover w3-padding-24</value>
      <webElementGuid>caac6227-4424-4fb6-93b7-5636381c3ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>b4a06dae-6c0b-45af-a2c3-d3bb7e5c22c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>w3_open_nav('tutorials')</value>
      <webElementGuid>98b83b46-8f80-4684-bc7c-4d6dd3517e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navbtn_tutorials</value>
      <webElementGuid>1b94512c-b718-4dc5-b609-9ec85da69e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tutorials</value>
      <webElementGuid>581a0d13-761b-442e-b6d1-1a6ed9658581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tutorials </value>
      <webElementGuid>b989d77e-b9df-4eec-a640-f02e198dbac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbtn_tutorials&quot;)</value>
      <webElementGuid>99cdfc30-0c13-467a-95bd-3c63d0fe63bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='navbtn_tutorials']</value>
      <webElementGuid>a548b114-a02a-4b12-9f37-12b7f9962047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tutorials')]</value>
      <webElementGuid>f1569166-9185-478f-9fe8-8715e6eb802b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='References'])[1]/preceding::a[1]</value>
      <webElementGuid>a09e21b2-ff02-4551-b86a-dc9166a8472e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exercises'])[1]/preceding::a[2]</value>
      <webElementGuid>61ce5ea6-b8a2-4661-9dde-3fe183234c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tutorials']/parent::*</value>
      <webElementGuid>1e02ba96-5e0d-4848-b383-947dcd8e2114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>c97fc864-d251-4a15-a883-225f4aec011d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>4e8816df-f49e-4ab7-b780-647c33ce645a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'navbtn_tutorials' and @title = 'Tutorials' and (text() = 'Tutorials ' or . = 'Tutorials ')]</value>
      <webElementGuid>a5406cc3-ccb5-454e-aa9f-ab0334000b02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
