<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Learn CSS</name>
   <tag></tag>
   <elementGuidId>82d58bc5-e27f-431e-86be-b87cf1ee8ac6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='nav_tutorials']/div/div/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ee8b99cf-6b9c-4d7c-8b5e-944bd89d34f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-bar-item w3-button</value>
      <webElementGuid>565d489d-caa4-492c-91f6-3ef1c3537817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/css/default.asp</value>
      <webElementGuid>498ee86b-b4b5-46ed-888c-c9a24e38b9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Learn CSS</value>
      <webElementGuid>e2ae8a9e-24eb-4ff5-881e-db7c2f45cb3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav_tutorials&quot;)/div[@class=&quot;w3-content&quot;]/div[@class=&quot;w3-row-padding w3-bar-block&quot;]/div[@class=&quot;w3-col l3 m6&quot;]/a[@class=&quot;w3-bar-item w3-button&quot;]</value>
      <webElementGuid>0fe746da-a1b9-4070-a0de-4103ae73853d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='nav_tutorials']/div/div/div[2]/a[2]</value>
      <webElementGuid>bdb15770-92ca-4198-be4d-a3affa1bd822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Learn CSS')]</value>
      <webElementGuid>2b4b7e62-46e3-44ff-b21f-401b9c5192d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn HTML'])[1]/following::a[1]</value>
      <webElementGuid>4e0bbde7-0237-4b66-bb6d-c95854da271d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HTML and CSS'])[1]/following::a[2]</value>
      <webElementGuid>ab2e2b81-d9e5-4ff6-a057-a59e9d3b2d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn RWD'])[1]/preceding::a[1]</value>
      <webElementGuid>93d5bfed-bc7b-45f9-a407-f112eb39fbc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn Bootstrap'])[1]/preceding::a[2]</value>
      <webElementGuid>86628e04-4645-4087-99b3-46e9c793f35c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Learn CSS']/parent::*</value>
      <webElementGuid>f5ef6f6b-500d-4976-bffb-c3bbdc4a863a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/css/default.asp')]</value>
      <webElementGuid>4a6372bb-9b10-41b0-9b88-58a2d5c22f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/a[2]</value>
      <webElementGuid>445f888c-4332-416c-9db6-d1f878328e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/css/default.asp' and (text() = 'Learn CSS' or . = 'Learn CSS')]</value>
      <webElementGuid>46e24a2d-34fe-4744-926a-f68b21c90d2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
