<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tutorials</name>
   <tag></tag>
   <elementGuidId>ca290968-8a4d-4000-805d-30b8c6ae9b46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navbtn_tutorials</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navbtn_tutorials']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>221f1341-bd16-4ba5-a438-53a04a4d6a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-bar-item w3-button w3-hide-small barex bar-item-hover w3-padding-24 mystyle</value>
      <webElementGuid>49f82153-ca19-4947-878b-f68afe65a834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>68f9eeed-2d29-4c12-93a1-0fcac841962e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>w3_open_nav('tutorials')</value>
      <webElementGuid>f5028a8d-98db-439d-af8e-a360bf69be73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navbtn_tutorials</value>
      <webElementGuid>be53ba3a-3a2d-4533-a429-a1d5506c1732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tutorials</value>
      <webElementGuid>aedacebd-359a-4fb0-8233-bdd182cef07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tutorials </value>
      <webElementGuid>8dc7ad33-3a64-48c6-b8ba-2560948924cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbtn_tutorials&quot;)</value>
      <webElementGuid>ae9d8b1e-426b-4fa9-a3b7-8c86b920ae60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='navbtn_tutorials']</value>
      <webElementGuid>ffee5071-3abd-4d9d-bb00-7f3a3c6e0a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tutorials')]</value>
      <webElementGuid>0719017b-1200-49d3-bbf0-ecb68137db17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='References'])[1]/preceding::a[1]</value>
      <webElementGuid>4b54cc6c-7f91-440f-855d-e47a3a7063d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exercises'])[1]/preceding::a[2]</value>
      <webElementGuid>e33311fe-aaea-4b33-ba65-6bb9c3ca6df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tutorials']/parent::*</value>
      <webElementGuid>17fa3b22-7cbe-4dfd-a2c4-10c5b01080a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>552f0629-aa16-414e-8c4d-a7c488241eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>9673b35d-2763-4a6e-a4c8-e0eea31ff4f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'navbtn_tutorials' and @title = 'Tutorials' and (text() = 'Tutorials ' or . = 'Tutorials ')]</value>
      <webElementGuid>1f9b4f60-c184-4fac-8942-3d4cadb8b5ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
