<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Stok Kosong</name>
   <tag></tag>
   <elementGuidId>e886ef70-b9ed-4b0f-a4c0-64d273c3fa32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/div/div/section/section/div[6]/div[3]/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f4c9b49-832b-4c25-9bcd-0dcf3fab7c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-dfsrp1-18 eAVrfs</value>
      <webElementGuid>3b1862c8-38b8-4082-9ba9-c9812f9bebd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stok Kosong</value>
      <webElementGuid>fa4d8c27-71b8-46c8-ab8e-a0b3d77e43ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;sc-1dze5zo-0 lnpKeT&quot;]/section[@class=&quot;sc-1dze5zo-1 imPRYC&quot;]/section[@class=&quot;sc-60zcpy-1 klCJsD&quot;]/div[@class=&quot;sc-t5y2j2-0 cXypTy&quot;]/div[@class=&quot;sc-1crxk01-0 fPmRnc sc-t5y2j2-1 zqFzN&quot;]/div[@class=&quot;sc-1crxk01-0 lkwwJy sc-dfsrp1-1 cOOIyQ&quot;]/div[@class=&quot;sc-dfsrp1-16 aUZEl&quot;]/div[@class=&quot;sc-dfsrp1-18 eAVrfs&quot;]</value>
      <webElementGuid>2b9fe1e5-9b58-4117-9ed5-9aba75213faa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div/div/section/section/div[6]/div[3]/div[2]/div/div</value>
      <webElementGuid>93bd1a2a-0835-48f8-bb91-775c219531c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stok habis'])[1]/following::div[3]</value>
      <webElementGuid>e2b8863d-020f-4b0a-a2f2-fa48116edac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp655.620'])[1]/following::div[10]</value>
      <webElementGuid>53e11075-35f3-48f4-b4c7-118b04770c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shock Absorber / Breaker KAYABA 4W KYB - Premium Series untuk mobil Toyota Soluna (Shock Depan)'])[1]/preceding::div[2]</value>
      <webElementGuid>e87394d2-4e63-475c-ab7a-db9470d45e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>8c60204c-6ddb-451d-a0d2-0f2b76380e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Stok Kosong' or . = 'Stok Kosong')]</value>
      <webElementGuid>8532314e-37f8-498c-b144-24d5d6fc1368</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
