<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_1</name>
   <tag></tag>
   <elementGuidId>6c3c6144-a8f3-494b-937d-1c4b4df27c2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp1.081.000'])[1]/preceding::*[name()='svg'][6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>debbbc4d-b570-4ea7-930d-ba465ef4e170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>72e13624-60b2-42e9-bcf0-fd0031c37f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>94ed8f05-d815-4f59-b396-e33d87ada9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 16</value>
      <webElementGuid>59eb9aa1-b7f4-41d3-ac7c-0024c8349486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>f87a1f85-6f04-45b3-b797-74e43212bdca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>fe99f9f4-ac80-4558-9a25-1e229080fddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;sc-pk5e3p-0 fQUczW&quot;]/section[@class=&quot;sc-pk5e3p-1 ghbFQU&quot;]/header[@class=&quot;sc-16gfu33-0 eOChbP&quot;]/div[@class=&quot;sc-15itbtn-0 gijYLl&quot;]/div[@class=&quot;sc-1crxk01-0 opsQJ&quot;]/button[@class=&quot;sc-1nihjkh-2 llIXQU sc-30y1kl-0 cKCbuk&quot;]/div[@class=&quot;sc-30y1kl-2 ipeKqB&quot;]/span[@class=&quot;sc-rq82e3-0 dIFCfE sc-30y1kl-3 gczumF&quot;]/svg[1]</value>
      <webElementGuid>c1660f95-4b44-48c8-bd56-47b18c8c0702</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp1.081.000'])[1]/preceding::*[name()='svg'][6]</value>
      <webElementGuid>7ba0d331-9c15-47c1-9096-7e72213afadc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp972.900'])[1]/preceding::*[name()='svg'][6]</value>
      <webElementGuid>084ba284-64a6-4ca2-8924-e9977bf4e0ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
