<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_login_customer_email</name>
   <tag></tag>
   <elementGuidId>4ac2bec7-9820-4436-a636-c918ed3c1492</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='customer_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;customer_email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>354f5e20-f058-46ee-811d-100ca786572c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field</value>
      <webElementGuid>1df904b0-7764-47d0-bbe2-fe0047a72655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>c6c9ed78-368b-41a7-9b0d-5f4a959bdec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer_email</value>
      <webElementGuid>c69d32cf-17f0-4b40-86cf-4bb1dcade5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>f0eba63b-c070-4fa0-a37b-d2483781e69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-login-route&quot;)/div[@class=&quot;login-body&quot;]/input[@class=&quot;text-field&quot;]</value>
      <webElementGuid>22136a87-b5cf-40a1-ad03-3c4defded9d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='customer_email']</value>
      <webElementGuid>fc83b7d9-1393-44d6-b234-3449a0ddca61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-login-route']/div/input</value>
      <webElementGuid>66b0c0ff-f08b-4b9f-ad42-4c4b74900675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>6c995e31-5529-4fc9-9f1e-e235406d6ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'customer_email' and @placeholder = 'email']</value>
      <webElementGuid>7c94551f-2320-4e84-bc39-6d2213091dd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
