<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CSS Backgrounds</name>
   <tag></tag>
   <elementGuidId>46911b42-73f8-4113-856b-424657d89fb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.active_overview</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftmenuinnerinner']/a[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fed147c3-652f-4e7a-94cb-1f4a4c017c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>4accee03-18c4-410c-9b38-1dbe224903e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>css_background.asp</value>
      <webElementGuid>7f61d2f3-30da-401d-832d-56cdec1e6d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active_overview</value>
      <webElementGuid>8031f18f-3287-4bc5-95aa-ce9b2da3646b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CSS Backgrounds</value>
      <webElementGuid>77012214-4427-4755-a639-5f5f9bca065f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftmenuinnerinner&quot;)/a[@class=&quot;active_overview&quot;]</value>
      <webElementGuid>63b3bb57-ae35-4811-991f-a9cf47a43326</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftmenuinnerinner']/a[8]</value>
      <webElementGuid>4c9a2ee7-02a6-4805-9d73-0a6ae2cfe54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CSS Backgrounds')]</value>
      <webElementGuid>5aabb5f2-3d6b-4709-a979-01f3f32a9f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HSL'])[1]/following::a[1]</value>
      <webElementGuid>454eba85-03ac-4eca-a8ee-ff1fb67a62c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HEX'])[1]/following::a[2]</value>
      <webElementGuid>b90b4e1c-baa7-42b6-961d-c0204b75ec3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Background Color'])[1]/preceding::a[1]</value>
      <webElementGuid>da4d5f76-0b3e-4ad4-96fc-9b87e8c84193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Background Image'])[1]/preceding::a[2]</value>
      <webElementGuid>759ff4f3-cfe2-4c78-b511-e38624de4358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'css_background.asp')]</value>
      <webElementGuid>8fc62e85-110d-48b0-8014-4fd1e201fb08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/a[8]</value>
      <webElementGuid>39af0ede-d857-4df3-a81b-ea80774a2e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'css_background.asp' and (text() = 'CSS Backgrounds' or . = 'CSS Backgrounds')]</value>
      <webElementGuid>742e121c-7ed3-48f6-b82e-2a0504496e18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
