<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CSS Selectors</name>
   <tag></tag>
   <elementGuidId>aaac3193-aa3b-4dab-b28c-fdb64bf248ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leftmenuinnerinner > a.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftmenuinnerinner']/a[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6904dde2-2f91-448f-a853-bc0246d8df59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>a87aeaa5-0b9f-4bcd-9ac7-451e6a93efcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>css_selectors.asp</value>
      <webElementGuid>6ca3308c-d91f-4f01-817f-473a7ad2a6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>67942651-a03b-44e8-9ced-45d1596fe604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CSS Selectors</value>
      <webElementGuid>10ee9603-de82-4f48-8626-9498734d0da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftmenuinnerinner&quot;)/a[@class=&quot;active&quot;]</value>
      <webElementGuid>17099491-93b2-423f-aa38-09c2b2456570</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftmenuinnerinner']/a[4]</value>
      <webElementGuid>8ac5dd97-d1d5-4a18-a0d9-5ef92814a58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CSS Selectors')]</value>
      <webElementGuid>b8760814-d927-4d90-8cb3-d9c653d32cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSS Syntax'])[1]/following::a[1]</value>
      <webElementGuid>9187cf91-f7eb-4ed9-bca1-05d0a068bf05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSS Introduction'])[1]/following::a[2]</value>
      <webElementGuid>37244708-e5c2-4d9f-9dbe-1e31953be99b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSS How To'])[1]/preceding::a[1]</value>
      <webElementGuid>a3a1baf3-951b-40cc-9c19-1bb671bad8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSS Comments'])[1]/preceding::a[2]</value>
      <webElementGuid>3f2a65d2-a1d9-4e08-bf3a-f72dd18804c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'css_selectors.asp')])[2]</value>
      <webElementGuid>efdd57bb-c3f6-40cb-9b11-66f4428e9f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/a[4]</value>
      <webElementGuid>343a8696-f2b7-4b76-ad6e-3be784a139fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'css_selectors.asp' and (text() = 'CSS Selectors' or . = 'CSS Selectors')]</value>
      <webElementGuid>2f74e4c4-fb62-420c-8fd9-55cce1b9f689</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
