<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gabungkan</name>
   <tag></tag>
   <elementGuidId>0210b21e-83fd-4fd7-84bd-4fb9042b7965</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='megaMenu']/div/div/div/div[2]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f0036ad7-7dc0-4a8c-88c6-c18ebaf96009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>merge-pdf</value>
      <webElementGuid>7350fa0d-1f11-4293-8b85-dd3eb769544d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Gabungkan beberapa PDF dan gambar menjadi satu</value>
      <webElementGuid>34ab520b-0515-42a4-932a-24c437de0afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip175372</value>
      <webElementGuid>4cb7d896-ef34-4ce9-b024-17cbc11e48e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gabungkan</value>
      <webElementGuid>fc1d116c-278f-4fb4-82ba-42c96989c9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;megaMenu&quot;)/div[@class=&quot;mega-menu-inner&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-sm-2 col-md-5ths&quot;]/ul[1]/li[3]/a[1]</value>
      <webElementGuid>3de44c27-50ff-4813-bd10-789782b4eb14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='megaMenu']/div/div/div/div[2]/ul/li[3]/a</value>
      <webElementGuid>cb43705f-54a7-49ec-954d-bb0ecd95d67b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Gabungkan')])[3]</value>
      <webElementGuid>4e4a7b6f-bd60-46fe-8ed7-c0befa67fffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alternasi &amp; Campur'])[1]/following::a[1]</value>
      <webElementGuid>5cc850b4-c1dc-4d40-8de6-ce38b2986d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gabungkan'])[3]/following::a[2]</value>
      <webElementGuid>a62c504a-d0ba-4d0d-9c8f-94134f4334dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organize'])[1]/preceding::a[1]</value>
      <webElementGuid>c7f583a3-02aa-4459-8766-e3cdc48b9e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pisahkan'])[1]/preceding::a[2]</value>
      <webElementGuid>cf5d9509-59c3-4ecb-ad9a-209963bbec4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'merge-pdf')])[3]</value>
      <webElementGuid>3af0ceb9-a058-4bb5-8066-c13fad526951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]/a</value>
      <webElementGuid>da210020-ba81-4812-a7df-57079ba5a8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'merge-pdf' and (text() = 'Gabungkan' or . = 'Gabungkan')]</value>
      <webElementGuid>16b6c0e3-469a-4f2b-a13b-85175ee3832a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
